---

plugins:
  - import
  - jest
  - fp

env:
  node: true
  jest: true
  browser: true

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"
  - 'plugin:fp/recommended'

parserOptions:
  ecmaVersion: 11
  sourceType: module

rules:
  no-console: 0
  fp/no-nil: 0
  fp/no-unused-expression: 0
  fp/no-throw: 0
  fp/no-mutation: ["error", {
    "commonjs": true,
  }]
  import/extensions: 0
  no-await-in-loop: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]